# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build static site

on:
  push:
    branches: [ master, preview ]
  pull_request:
    branches: [ master ]

jobs:
  nuxt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build static site
      run: yarn generate
    - uses: actions/upload-artifact@v1.0.0
      with: 
        name: dist
        path: dist/ 
  # docker:
  #   needs: nuxt
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/download-artifact@v1
  #     with:
  #       name: dist
  #   - name: download caddy
  #     run: |
  #       curl -L -o caddy2.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.0.0/caddy_2.0.0_linux_amd64.tar.gz
  #       tar xf caddy2.tar.gz
  #   - name: build Docker
  #     run: docker build . --file Dockerfile --tag personalpage
  #   - name: publish docker
  #     run: |
  #       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #       docker tag personalpage ${{ secrets.DOCKER_USERNAME }}/personalpage
  #       docker push ${{ secrets.DOCKER_USERNAME }}/personalpage


    
